$dir =  "C:\packagesoffline"

# Create the folder is the path doesn't exist
If (-not(test-path -Path $dir)) {
    New-Item  -ItemType Directory -Path $dir
}

# tcpkg download TC1300.Cpp.XAE -o "C:\packagesoffline"
# tcpkg download TC170x.UsermodeRuntime.XAR -o "C:\packagesoffline"
# tcpkg download TE1120.XCADInterface.XAE -o "C:\packagesoffline"
# tcpkg download TE1300.ScopeViewProfessional.XAE -o "C:\packagesoffline"
# tcpkg download TE1310.FilterDesigner.XAE -o "C:\packagesoffline"
# tcpkg download TE1320.BodePlotBase.XAE -o "C:\packagesoffline"
# tcpkg download TE1400.TargetForSimulink.XAE -o "C:\packagesoffline"
# tcpkg download TE1401.TargetForMATLAB.XAE -o "C:\packagesoffline"
# tcpkg download TE1410.InterfaceForMATLABSimulink.XAE -o "C:\packagesoffline"
# tcpkg download TE1610.EAPConfigurator.XAE -o "C:\packagesoffline"
# tcpkg download TE2000.HMIEngineering.XAE -o "C:\packagesoffline"
# tcpkg download TE5910.MotionDesigner.XAE -o "C:\packagesoffline"
# tcpkg download TE5950.DriveManager2.XAE -o "C:\packagesoffline"
# tcpkg download TE6100.OpcUaNodesetEditor.XAE  -o "C:\packagesoffline"
# tcpkg download TF1200.UiClient.XAR  -o "C:\packagesoffline"
# tcpkg download TF1800.PLCHMI.XAR  -o "C:\packagesoffline"
# tcpkg download TF1810.PLCHMIWeb.XAR  -o "C:\packagesoffline"
# tcpkg download TF2000.HMIServer.XAR  -o "C:\packagesoffline"
# tcpkg download TF3300.ScopeServer.XAR  -o "C:\packagesoffline"
# tcpkg download TF3500.AnalyticsLogger.XAE  -o "C:\packagesoffline"
# tcpkg download TF3510.AnalyticsLibrary.XAE  -o "C:\packagesoffline"
# tcpkg download TF3520.AnalyticsStorageProvider.XAE  -o "C:\packagesoffline"
# tcpkg download TF3520.AnalyticsStorageProvider.XAR  -o "C:\packagesoffline"
# tcpkg download TF3551.AnalyticsRuntimeBase.XAR  -o "C:\packagesoffline"
# tcpkg download TF3600.ConditionMonitoring.XAE  -o "C:\packagesoffline"
# tcpkg download TF3650.PowerMonitoring.XAE  -o "C:\packagesoffline"
# tcpkg download TF3680.FilterLibrary.XAE  -o "C:\packagesoffline"
# tcpkg download TF3685.WeighingLibrary.XAE  -o "C:\packagesoffline"
# tcpkg download TF3710.InterfaceForLabVIEW.XAE  -o "C:\packagesoffline"
# tcpkg download TF3900.SolarPositionAlgorithm.XAE  -o "C:\packagesoffline"
# tcpkg download TF4100.ControllerToolbox.XAE  -o "C:\packagesoffline"
# tcpkg download TF4110.TemperatureController.XAE  -o "C:\packagesoffline"
# tcpkg download TF5000.NCPTP.XAE  -o "C:\packagesoffline"
# tcpkg download TF5000.NCPTP.XAR  -o "C:\packagesoffline"
# tcpkg download TF5100.NCI.XAE  -o "C:\packagesoffline"
# tcpkg download TF5100.NCI.XAR  -o "C:\packagesoffline"
# tcpkg download TF5120.Robotics-mxAutomation.XAE  -o "C:\packagesoffline"
# tcpkg download TF5130.Robotics-univalPLC.XAE  -o "C:\packagesoffline"
# tcpkg download TF5200.CNC.XAE  -o "C:\packagesoffline"
# tcpkg download TF5210.CNCE.XAE  -o "C:\packagesoffline"
# tcpkg download TF5210.CNCE.XAR  -o "C:\packagesoffline"
# tcpkg download TF5400.AdvancedMotionPack.XAE  -o "C:\packagesoffline"
# tcpkg download TF5400.AdvancedMotionPack.XAR  -o "C:\packagesoffline"
# tcpkg download TF5810.HydraulicPositioning.XAE  -o "C:\packagesoffline"
# tcpkg download TF5850.XTS.XAE  -o "C:\packagesoffline"
# tcpkg download TF6100.OpcUaConfigurator.XAE  -o "C:\packagesoffline"
# tcpkg download TF6100.OpcUaGateway.XAR  -o "C:\packagesoffline"
# tcpkg download TF6100.OpcUaServer.XAE  -o "C:\packagesoffline" -o "C:\packagesoffline"
# tcpkg download TF6100.OpcUaServer.XAR  -o "C:\packagesoffline"
# tcpkg download TF610x.OpcUaClientPubSub.XAE  -o "C:\packagesoffline"
# tcpkg download TF610x.OpcUaClientPubSub.XAR  -o "C:\packagesoffline"
# tcpkg download TF6230.ParallelRedundancyProtocol.XAE  -o "C:\packagesoffline"
# tcpkg download TF6250.ModbusTCP.XAE  -o "C:\packagesoffline"
# tcpkg download TF6250.ModbusTCP.XAR  -o "C:\packagesoffline"
# tcpkg download TF6255.ModbusRTU.XAE  -o "C:\packagesoffline"
# tcpkg download TF6255.ModbusRTU.XAR  -o "C:\packagesoffline"
# tcpkg download TF6310.TcpIp.XAE  -o "C:\packagesoffline"
# tcpkg download TF6310.TcpIp.XAR  -o "C:\packagesoffline"
# tcpkg download TF6340.SerialCommunication.XAE -o "C:\packagesoffline"
# tcpkg download TF6340.SerialCommunication.XAR -o "C:\packagesoffline"
# tcpkg download TF6420.DatabaseServer.XAE -o "C:\packagesoffline"
# tcpkg download TF6420.DatabaseServer.XAR -o "C:\packagesoffline"
# tcpkg download TF6421.XMLServer.XAE -o "C:\packagesoffline"
# tcpkg download TF6421.XMLServer.XAR -o "C:\packagesoffline"
# tcpkg download TF6500.IEC60870-5-10x.XAE -o "C:\packagesoffline"
# tcpkg download TF6500.IEC60870-5-10x.XAR  -o "C:\packagesoffline"
# tcpkg download TF6510.IEC61850-IEC61400-25.XAE -o "C:\packagesoffline"
# tcpkg download TF6510.IEC61850-IEC61400-25.XAR -o "C:\packagesoffline"
# tcpkg download TF6600.RFIDReaderCommunication.XAE -o "C:\packagesoffline"
# tcpkg download TF6600.RFIDReaderCommunication.XAR -o "C:\packagesoffline"
# tcpkg download TF6620.S7Communication.XAE -o "C:\packagesoffline"
# tcpkg download TF6620.S7Communication.XAR -o "C:\packagesoffline"
# tcpkg download TF6701.IotCommunication.XAE -o "C:\packagesoffline"
# tcpkg download TF6710.IotFunctions.XAE -o "C:\packagesoffline"
# tcpkg download TF6720.IotDataAgent.XAE -o "C:\packagesoffline"
# tcpkg download TF6720.IotDataAgent.XAR -o "C:\packagesoffline"
# tcpkg download TF6730.IotCommunicator.XAE -o "C:\packagesoffline"
# tcpkg download TF6760.IotHttpsRest.XAE -o "C:\packagesoffline"
# tcpkg download TF6770.IotWebSockets.XAE -o "C:\packagesoffline"
# tcpkg download TF6771.IotOCPP.XAE -o "C:\packagesoffline"
# tcpkg download TF7xxx.Vision.XAE -o "C:\packagesoffline"
# tcpkg download TF7xxx.Vision.XAR -o "C:\packagesoffline"
# tcpkg download TF8020.BACnet.XAE -o "C:\packagesoffline"
# tcpkg download TF8020.BACnet.XAR -o "C:\packagesoffline"
# tcpkg download TwinCAT.DriveManagerClassic.XAE -o "C:\packagesoffline"
# tcpkg download TwinCAT.Standard.XAE -o "C:\packagesoffline"
# tcpkg download TwinCAT.Standard.XAR -o "C:\packagesoffline"
# tcpkg download TwinCAT.StandardRM.XAE -o "C:\packagesoffline"


tcpkg download TwinCAT.Standard.XAE TwinCAT.Standard.XAR TwinCAT.StandardRM.XAE -o $dir